# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A ARMA series sampler using Rcpp
#' @description A ARMA series sampler using Rcpp
#' @param p  order of autoregression
#' @param q  order of moving average
#' @param n  length of time series
#' @param arParams a vector of autoregression parameters
#' @param maParams a vector of moving average parameters
#' @return the desired arma series
#' @useDynLib SA23204170
#' @examples
#' \dontrun{
#' error<- generateARMA(3,4,1000,c(.5,-.2),.3)
#' }
#' @export
generateARMA <- function(p, q, n, arParams, maParams) {
    .Call('_SA23204170_generateARMA', PACKAGE = 'SA23204170', p, q, n, arParams, maParams)
}

#' @title A Gibbs sampler
#' @description A Gibbs sampler
#' @param N number of samples
#' @param n number of trials 
#' @param a non-negative parameters of the Beta distribution.
#' @param b non-negative parameters of the Beta distribution.
#' @useDynLib SA23204170
#' @export
gibbsC <- function(N, n, a, b) {
    .Call('_SA23204170_gibbsC', PACKAGE = 'SA23204170', N, n, a, b)
}

